[package]
name = "scrapping"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
scraper = "0.22.0"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
